import {isConfigured,ensureAnonymousUser,select,insert,remove} from './lib/supabase.js';
import {buildStats,generateGames,rankTicket,createAISnapshot} from './lib/stats.js';
const qs=(s,e=document)=>e.querySelector(s),qsa=(s,e=document)=>[...e.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const ball=n=>`<span class="ball b${Math.ceil(n/10)}">${n}</span>`;
let state={draws:[],statGames:[],aiGames:[],aiScenario:'',tickets:[],page:'recommend',count:5,fixed:[],mode:'statistics',loading:false};
async function loadDraws(){const r=await fetch('/data/lotto.json');if(!r.ok)throw new Error('기본 로또 데이터를 불러오지 못했습니다.');const raw=await r.json(),merged=new Map(raw.map(x=>[Number(x.draw_no),{draw_no:Number(x.draw_no),draw_date:String(x.date||x.draw_date||'').slice(0,10),numbers:(x.numbers||[]).map(Number).sort((a,b)=>a-b),bonus_no:Number(x.bonus_no)}]));if(isConfigured)try{for(const row of await select('lotto_draws','select=draw_no,draw_date,numbers,bonus_no&order=draw_no.asc')||[])merged.set(Number(row.draw_no),{...row,draw_no:Number(row.draw_no),numbers:(row.numbers||[]).map(Number).sort((a,b)=>a-b)});}catch(e){console.warn(e);}state.draws=[...merged.values()].sort((a,b)=>a.draw_no-b.draw_no);}
async function loadTickets(){if(!isConfigured){state.tickets=JSON.parse(localStorage.getItem('lotto-tickets')||'[]');return;}try{await ensureAnonymousUser();state.tickets=await select('saved_tickets','select=*&order=created_at.desc')||[];}catch(e){console.warn(e);state.tickets=[];}}
const nav=()=>`<nav>${[['recommend','번호추천'],['stats','통계'],['tickets','내 번호'],['admin','관리자']].map(([k,v])=>`<button type="button" data-page="${k}" class="${state.page===k?'active':''}">${v}</button>`).join('')}</nav>`;
function header(){const latest=state.draws.at(-1);return `<header><div><p class="eyebrow">LOTTO 6/45</p><h1>데이터·AI 번호 추천기</h1><p>통계 모델과 Gemini의 조건부 예측 시나리오를 비교합니다.</p></div><div class="latest"><small>최신 데이터</small><strong>${latest?.draw_no||'-'}회</strong><span>${latest?.draw_date||''}</span></div></header>`;}
function modeControl(){return `<div class="segmented" role="radiogroup">${[['statistics','📊 통계 추천'],['ai','🤖 Gemini AI'],['both','🔀 둘 다']].map(([k,v])=>`<button type="button" data-mode="${k}" class="${state.mode===k?'active':''}">${v}</button>`).join('')}</div>`;}
function gameCard(g,i,type){return `<div class="gameCard ${type}"><div class="game"><b>${type==='ai'?'AI':'통계'} ${i+1}게임</b><div>${g.numbers.map(ball).join('')}</div><button type="button" data-save-numbers="${g.numbers.join(',')}">저장</button></div>${type==='statistics'?`<div class="gameMeta"><strong>추천지수 ${g.score}점</strong></div>`:`<div class="aiReason"><strong>Gemini 선택 이유</strong><p>${esc(g.reason)}</p></div>`}</div>`;}
function recommend(){const fixed=Array.from({length:45},(_,i)=>i+1).map(n=>`<button type="button" class="pick ${state.fixed.includes(n)?'on':''}" data-fixed="${n}">${n}</button>`).join('');const showStat=state.mode!=='ai',showAI=state.mode!=='statistics';return `<section class="grid"><article class="card controls"><h2>추천 방식</h2>${modeControl()}<label>게임 수 <b id="countLabel">${state.count}</b><input id="count" type="range" min="1" max="10" value="${state.count}"></label><details><summary>고정 번호 선택 (${state.fixed.length}/5)</summary><div class="picker">${fixed}</div></details><button type="button" class="primary" id="generate" ${state.loading?'disabled':''}>${state.loading?'분석 중…':'번호 생성'}</button><p class="hint">통계 추천은 과거 데이터 적합도 점수를 표시합니다. Gemini 추천은 데이터에서 관찰되는 추세 지속·평균 회귀 등의 가설을 세우고 조합과 이유를 제시합니다. 어느 방식도 실제 당첨을 보장하지 않습니다.</p></article><article class="card results"><div class="titleRow"><h2>추천 결과</h2></div>${state.loading?'<div class="loading"><span></span><b>통계와 시간 흐름을 분석하고 있습니다…</b></div>':''}${showStat&&state.statGames.length?`<h3 class="sectionTitle">📊 통계 모델</h3>${state.statGames.map((g,i)=>gameCard(g,i,'statistics')).join('')}`:''}${showAI&&state.aiGames.length?`<h3 class="sectionTitle">🤖 Gemini AI</h3>${state.aiScenario?`<div class="scenario"><strong>예측 시나리오</strong><p>${esc(state.aiScenario)}</p></div>`:''}${state.aiGames.map((g,i)=>gameCard(g,i,'ai')).join('')}`:''}${!state.loading&&!state.statGames.length&&!state.aiGames.length?'<div class="empty">추천 방식을 고르고 번호를 생성해보세요.</div>':''}</article></section>`;}
function statsPage(){const s=buildStats(state.draws),rows=Array.from({length:45},(_,i)=>i+1).map(n=>({n,total:s.total[n],recent:s.recent50[n],overdue:s.overdue[n]})).sort((a,b)=>b.total-a.total);return `<section class="card"><h2>번호 통계</h2><p class="hint">총 ${state.draws.length}개 회차 기준 · 최근 50회 포함</p><div class="tableWrap"><table><thead><tr><th>번호</th><th>전체 출현</th><th>최근 50회</th><th>미출현</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${ball(x.n)}</td><td>${x.total}회</td><td>${x.recent}회</td><td>${x.overdue}회차</td></tr>`).join('')}</tbody></table></div></section>`;}
function ticketsPage(){return `<section class="card"><div class="titleRow"><h2>내 번호</h2><button type="button" id="manualTicket">직접 추가</button></div>${state.tickets.length?state.tickets.map(t=>{const draw=state.draws.find(d=>d.draw_no===Number(t.target_draw_no)),r=rankTicket(t.numbers,draw);return `<div class="ticket"><div><strong>${esc(t.label||'저장 번호')}</strong><small>${t.target_draw_no?`${t.target_draw_no}회 · ${r.label}`:'회차 미지정'}</small></div><div>${t.numbers.map(ball).join('')}</div><button type="button" class="danger" data-delete="${t.id}">삭제</button></div>`;}).join(''):'<div class="empty">저장한 번호가 없습니다.</div>'}</section>`;}
function adminPage(){const next=(state.draws.at(-1)?.draw_no||0)+1;return `<section class="grid"><article class="card"><h2>최신 회차 수동 입력</h2><form id="manualDraw"><label>관리 비밀번호<input name="secret" type="password" required></label><label>회차<input name="draw_no" type="number" value="${next}" required></label><label>추첨일<input name="draw_date" type="date" required></label><label>당첨번호 6개<input name="numbers" placeholder="예: 1, 7, 15, 22, 31, 43" required></label><label>보너스번호<input name="bonus_no" type="number" min="1" max="45" required></label><button class="primary">Supabase에 저장·업데이트</button></form></article><article class="card"><h2>외부 데이터 동기화</h2><form id="sync"><label>관리 비밀번호<input name="secret" type="password" required></label><button>GitHub 전체 데이터 동기화</button></form><div id="adminMessage" class="message"></div></article></section>`;}
function render(){qs('#root').innerHTML=`<main>${header()}${nav()}${state.page==='recommend'?recommend():state.page==='stats'?statsPage():state.page==='tickets'?ticketsPage():adminPage()}<footer>추천은 과거 데이터 기반 분석·추론이며 실제 당첨 확률을 높인다는 뜻이 아닙니다.</footer></main>`;bindForms();}
function bindForms(){const count=qs('#count');if(count)count.oninput=e=>{state.count=Number(e.target.value);qs('#countLabel').textContent=state.count;};const md=qs('#manualDraw');if(md)md.onsubmit=manualDraw;const sy=qs('#sync');if(sy)sy.onsubmit=syncDraws;}
async function generate(){state.loading=true;state.statGames=[];state.aiGames=[];state.aiScenario='';render();try{if(state.mode!=='ai')state.statGames=generateGames(state.draws,state.count,state.fixed);if(state.mode!=='statistics'){const candidates=generateGames(state.draws,Math.min(60,Math.max(30,state.count*8)),state.fixed).map(g=>({numbers:g.numbers,score:g.score}));const r=await fetch('/api/gemini-recommend',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({count:state.count,fixed:state.fixed,snapshot:createAISnapshot(state.draws),candidates})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Gemini 추천 실패');state.aiGames=j.games;state.aiScenario=j.scenario;} }catch(e){alert(e.message);}finally{state.loading=false;render();}}
async function saveTicket(numbers){const target=Number(prompt('대상 회차를 입력하세요.',String((state.draws.at(-1)?.draw_no||0)+1)))||null,label=prompt('메모 또는 이름을 입력하세요.','추천 번호')||'추천 번호';if(isConfigured){const user=await ensureAnonymousUser();try{const data=await insert('saved_tickets',{user_id:user.id,label,target_draw_no:target,numbers});state.tickets.unshift(data);}catch(e){return alert(e.message);}}else{const t={id:crypto.randomUUID(),label,target_draw_no:target,numbers,created_at:new Date().toISOString()};state.tickets.unshift(t);localStorage.setItem('lotto-tickets',JSON.stringify(state.tickets));}alert('저장했습니다.');}
async function deleteTicket(id){if(!confirm('삭제할까요?'))return;if(isConfigured)try{await remove('saved_tickets',id);}catch(e){return alert(e.message);}state.tickets=state.tickets.filter(t=>String(t.id)!==String(id));localStorage.setItem('lotto-tickets',JSON.stringify(state.tickets));render();}
async function manualTicket(){const raw=prompt('번호 6개를 쉼표로 입력하세요.','1, 7, 15, 22, 31, 43');if(!raw)return;const nums=raw.split(/[ ,]+/).map(Number).filter(Boolean);if(nums.length!==6||new Set(nums).size!==6||nums.some(n=>n<1||n>45))return alert('1~45의 서로 다른 번호 6개를 입력하세요.');await saveTicket(nums.sort((a,b)=>a-b));render();}
async function manualDraw(e){e.preventDefault();const f=new FormData(e.currentTarget),nums=String(f.get('numbers')).split(/[ ,]+/).map(Number).filter(Number.isFinite),body={secret:f.get('secret'),draw_no:Number(f.get('draw_no')),draw_date:f.get('draw_date'),numbers:nums,bonus_no:Number(f.get('bonus_no'))};if(nums.length!==6||new Set(nums).size!==6||nums.some(n=>n<1||n>45))return alert('당첨번호 6개를 정확히 입력하세요.');if(nums.includes(body.bonus_no))return alert('보너스 번호는 당첨번호와 달라야 합니다.');if(state.draws.some(d=>d.draw_no===body.draw_no)&&!confirm('이미 있는 회차입니다. 기존 값을 수정할까요?'))return;const r=await fetch('/api/manual-draw',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),j=await r.json();if(!r.ok)return alert(j.error||'저장 실패');await loadDraws();state.statGames=[];state.aiGames=[];alert(`${body.draw_no}회 저장 완료. 기존 데이터에 추가 반영했습니다.`);render();}
async function syncDraws(e){e.preventDefault();const f=new FormData(e.currentTarget),r=await fetch('/api/sync-lotto',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({secret:f.get('secret')})}),j=await r.json();if(!r.ok)return qs('#adminMessage').textContent=j.error||'동기화 실패';await loadDraws();state.statGames=[];state.aiGames=[];render();}
function installDelegation(){document.addEventListener('click',async e=>{const page=e.target.closest('[data-page]');if(page){state.page=page.dataset.page;render();return;}const mode=e.target.closest('[data-mode]');if(mode){state.mode=mode.dataset.mode;state.statGames=[];state.aiGames=[];state.aiScenario='';render();return;}const fixed=e.target.closest('[data-fixed]');if(fixed){const n=Number(fixed.dataset.fixed);state.fixed=state.fixed.includes(n)?state.fixed.filter(x=>x!==n):state.fixed.length<5?[...state.fixed,n]:state.fixed;render();return;}if(e.target.closest('#generate'))return generate();const save=e.target.closest('[data-save-numbers]');if(save)return saveTicket(save.dataset.saveNumbers.split(',').map(Number));const del=e.target.closest('[data-delete]');if(del)return deleteTicket(del.dataset.delete);if(e.target.closest('#manualTicket'))return manualTicket();});}
export async function createApp(){installDelegation();await Promise.all([loadDraws(),loadTickets()]);render();}
